### ISSUE TITLE
List code references

### ISSUE THREAD

**Issue by franziskuskiefer** [openmls/validation.dhall#11]
Add code references for all checks and add issues (or reference existing issues) for every check.

**Comment by franziskuskiefer** [comment]
This may be a duplicate of #1 . Feel free to close one if you think that's the case.

**Comment by keks** [comment]
I went through the code and documented everything I could find, but I may have missed some checks. I also didn't capture the tests, because these are a bit spread out as well. But we now have a shortlist of things we need to fix, or at least double check, which is a good start.

I am closing this for now.
